# Turn on logging, and set ZMK logging to debug output
CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=34
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=0
CONFIG_BT_MAX_CONN=4
CONFIG_BT_MAX_PAIRED=4
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Display from dongle_display module
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_IDLE_TIMEOUT=300000

# Optional: Show dongle's own battery
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=n

# Display modules
CONFIG_ZMK_DONGLE_DISPLAY_WPM=n
CONFIG_ZMK_DONGLE_DISPLAY_BONGO_CAT=n
CONFIG_ZMK_HID_INDICATORS=n
